apiVersion: v1
kind: ConfigMap
metadata:
  name: ui
data:
  ENDPOINTS_CATALOG: http://catalog
  ENDPOINTS_CARTS: http://carts
  ENDPOINTS_CHECKOUT: http://checkout
  ENDPOINTS_ORDERS: http://orders
  ENDPOINTS_ASSETS: http://assets

