apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-redis
  labels:
    app.kubernetes.io/name: checkout
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: checkout
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: checkout
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: "redis:6.0-alpine"
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP

