apiVersion: v1
kind: Service
metadata:
  name: checkout
  labels:
    app.kubernetes.io/name: checkout
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: checkout

