apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orders-rabbitmq
  labels:
    app.kubernetes.io/name: orders
    app.kubernetes.io/component: rabbitmq
spec:
  replicas: 1
  serviceName: orders-rabbitmq
  selector:
    matchLabels:
      app.kubernetes.io/name: orders
      app.kubernetes.io/component: rabbitmq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orders
        app.kubernetes.io/component: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "public.ecr.aws/docker/library/rabbitmq:3-management"
          ports:
            - name: amqp
              containerPort: 5672
            - name: http
              containerPort: 15672
          volumeMounts:
            - name: data
              mountPath: "/var/lib/rabbitmq/mnesia"
      volumes:
        - name: data
          emptyDir: {}

