apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: argocd
spec:
  secretName: argocd-tls-secret
  issuerRef:
    name: letsencrypt-production
    kind: Issuer
  dnsNames:
    - "argocd.alvaro.studentdumbways.my.id"
