apiVersion: v1
kind: Service
metadata:
  name: catalog-mysql
  labels:
    app: catalog
spec:
  selector:
    app: catalog
    component: mysql
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  type: ClusterIP

