apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets
  labels:
    app.kubernetes.io/name: assets
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: assets
  template:
    metadata:
      labels:
        app.kubernetes.io/name: assets
    spec:
      serviceAccountName: assets
      containers:
        - name: assets
          image: "public.ecr.aws/aws-containers/retail-store-sample-assets:0.8.2"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: assets
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 128m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health.html
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory

